# This is a config for E2B sandbox template.
# You can use template ID (fisn85gkwqx30g2w51pb) or template name (vibe-nextjs-akash-deep) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-akash-deep") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-akash-deep") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-akash-deep')

team_id = "0705d924-8352-410a-b71f-13b03b85a55e"
start_cmd = "compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-akash-deep"
template_id = "fisn85gkwqx30g2w51pb"
